### PR TITLE
Allow changing the Cookie class

### PR DESCRIPTION
**Pull request by laurentb**
Allow changing the Cookie class used by Cookies; otherwise, you cannot configure the parsers and validators to use in Cookies.

In the past I used to monkey-patch the Cookie class, which is less than ideal.

### CODE REVIEW

**Comment by sashahart** [comment]
Thanks very much for your report.

I'm looking at what to do about this, give me a few days.

**Comment by sashahart** [comment]
Although I am not really happy resorting to subclassing, I will admit I did not ever document the way of doing this that I originally had in mind. And I'd like to support you in doing this your way, sooner rather than later.

So I pushed a new version (fancifully called 2.0.0) and it is also available on PyPI.

Commit visible here:
https://github.com/sashahart/cookies/commit/4454494dd722e794328604dfa5f667dec016f8f0

**Comment by laurentb** [comment]
Thanks. My goal here is only to change a few parsers, mostly the one removing the dot before the domain, as many websites give it, and I want to create a replacement cookie jar for requests. Unless I am mistaken, the '.' has a special significance.

At least that what was I was doing 15 months earlier, and request's cookie management is better but still broken (because of cookielib). I might have other things to contribute then!

**Comment by sashahart** [comment]
I opened a new PR concerning the dot issue. It's a trivial change, the issue is what is the right thing to do. And I'm not sure so it's not merged yet.

https://github.com/sashahart/cookies/pull/5

**Pull request closed without merging**
